"""
Données seed pour le mock-site AniData Lab.
Liste d'animes populaires/réels utilisés pour générer le catalogue.

Quelques champs sont volontairement laissés vides ou "N/A" pour créer
des cas pédagogiques de gestion d'erreurs / valeurs manquantes.
"""

# Format : (title_en, title_jp, year, studio, type, episodes, status, genres, score, synopsis)
# score = None => sera rendu comme "N/A" dans le HTML
# studio = "" => sera rendu comme champ vide

ANIMES = [
    ("Attack on Titan", "進撃の巨人", 2013, "Wit Studio", "TV", 25, "Finished Airing",
     ["Action", "Drama", "Fantasy"], 9.0,
     "Dans un monde où l'humanité vit derrière d'immenses murs, Eren Yeager voit son village détruit par des Titans. Il rejoint alors le Bataillon d'Exploration pour se venger."),
    ("Death Note", "デスノート", 2006, "Madhouse", "TV", 37, "Finished Airing",
     ["Mystery", "Psychological", "Supernatural", "Thriller"], 8.6,
     "Light Yagami découvre un carnet qui permet de tuer quiconque dont le nom y est inscrit. Il décide de l'utiliser pour créer un monde parfait."),
    ("Fullmetal Alchemist: Brotherhood", "鋼の錬金術師", 2009, "Bones", "TV", 64, "Finished Airing",
     ["Action", "Adventure", "Drama", "Fantasy"], 9.1,
     "Edward et Alphonse Elric cherchent la Pierre Philosophale pour retrouver leurs corps, perdus lors d'une transmutation humaine interdite."),
    ("One Piece", "ワンピース", 1999, "Toei Animation", "TV", None, "Currently Airing",
     ["Action", "Adventure", "Comedy", "Shounen"], 8.7,
     "Monkey D. Luffy, un jeune pirate au corps en caoutchouc, parcourt les mers avec son équipage à la recherche du One Piece, le trésor ultime."),
    ("Naruto", "ナルト", 2002, "Studio Pierrot", "TV", 220, "Finished Airing",
     ["Action", "Adventure", "Shounen"], 8.0,
     "Naruto Uzumaki, un jeune ninja hyperactif, rêve de devenir Hokage, le chef de son village de Konoha."),
    ("Naruto: Shippuden", "ナルト 疾風伝", 2007, "Studio Pierrot", "TV", 500, "Finished Airing",
     ["Action", "Adventure", "Shounen"], 8.2,
     "Naruto revient à Konoha après deux ans d'entraînement pour affronter l'Akatsuki et sauver Sasuke."),
    ("Cowboy Bebop", "カウボーイビバップ", 1998, "Sunrise", "TV", 26, "Finished Airing",
     ["Action", "Drama", "Sci-Fi", "Space"], 8.8,
     "En 2071, un équipage de chasseurs de primes traverse le système solaire à bord du Bebop, chacun fuyant son propre passé."),
    ("Demon Slayer", "鬼滅の刃", 2019, "Ufotable", "TV", 26, "Finished Airing",
     ["Action", "Historical", "Supernatural"], 8.5,
     "Après le massacre de sa famille par un démon, Tanjiro Kamado devient pourfendeur pour sauver sa sœur transformée en démon."),
    ("My Hero Academia", "僕のヒーローアカデミア", 2016, "Bones", "TV", 13, "Finished Airing",
     ["Action", "Comedy", "School", "Super Power"], 8.0,
     "Dans un monde où 80% de la population a un pouvoir, Izuku Midoriya, né sans alter, rêve de devenir le plus grand héros."),
    ("Jujutsu Kaisen", "呪術廻戦", 2020, "MAPPA", "TV", 24, "Finished Airing",
     ["Action", "School", "Supernatural"], 8.6,
     "Yuji Itadori avale un doigt maudit et devient l'hôte de Ryomen Sukuna, un fléau légendaire."),
    ("Spirited Away", "千と千尋の神隠し", 2001, "Studio Ghibli", "Movie", 1, "Finished Airing",
     ["Adventure", "Supernatural", "Drama"], 8.8,
     "Chihiro se retrouve piégée dans un monde magique peuplé d'esprits après que ses parents ont été transformés en cochons."),
    ("Your Name", "君の名は", 2016, "CoMix Wave Films", "Movie", 1, "Finished Airing",
     ["Romance", "Supernatural", "Drama"], 8.9,
     "Deux adolescents, un garçon de Tokyo et une fille vivant à la campagne, échangent mystérieusement leurs corps dans leurs rêves."),
    ("Princess Mononoke", "もののけ姫", 1997, "Studio Ghibli", "Movie", 1, "Finished Airing",
     ["Adventure", "Fantasy", "Historical"], 8.7,
     "Ashitaka part en quête d'un remède à sa malédiction et se retrouve au cœur d'un conflit entre humains et esprits de la forêt."),
    ("Steins;Gate", "シュタインズ・ゲート", 2011, "White Fox", "TV", 24, "Finished Airing",
     ["Sci-Fi", "Thriller", "Drama"], 9.1,
     "Un groupe d'étudiants découvre accidentellement comment envoyer des messages dans le passé et se retrouve traqué par une mystérieuse organisation."),
    ("Code Geass", "コードギアス 反逆のルルーシュ", 2006, "Sunrise", "TV", 25, "Finished Airing",
     ["Action", "Drama", "Mecha", "Sci-Fi"], 8.7,
     "Lelouch obtient un pouvoir qui lui permet de commander à quiconque d'obéir à ses ordres, et décide de détruire l'Empire de Britannia."),
    ("Neon Genesis Evangelion", "新世紀エヴァンゲリオン", 1995, "Gainax", "TV", 26, "Finished Airing",
     ["Mecha", "Psychological", "Sci-Fi"], 8.4,
     "Shinji Ikari est recruté par son père pour piloter un Evangelion et défendre Tokyo-3 contre de mystérieuses créatures appelées Anges."),
    ("Hunter x Hunter (2011)", "ハンター×ハンター", 2011, "Madhouse", "TV", 148, "Finished Airing",
     ["Action", "Adventure", "Fantasy", "Shounen"], 9.0,
     "Gon Freecss devient chasseur pour retrouver son père, un légendaire Hunter qui l'a abandonné à la naissance."),
    ("Vinland Saga", "ヴィンランド・サガ", 2019, "Wit Studio", "TV", 24, "Finished Airing",
     ["Action", "Adventure", "Drama", "Historical"], 8.7,
     "Thorfinn, un jeune viking, cherche à venger la mort de son père dans une Europe médiévale déchirée par les guerres."),
    ("Mob Psycho 100", "モブサイコ100", 2016, "Bones", "TV", 12, "Finished Airing",
     ["Action", "Comedy", "Supernatural"], 8.5,
     "Shigeo Kageyama, dit Mob, est un collégien doté de pouvoirs psychiques immenses qu'il tente de garder sous contrôle."),
    ("One Punch Man", "ワンパンマン", 2015, "Madhouse", "TV", 12, "Finished Airing",
     ["Action", "Comedy", "Super Power"], 8.5,
     "Saitama est un héros tellement puissant qu'il bat tous ses adversaires d'un seul coup de poing, ce qui le déprime profondément."),
    ("Bleach", "ブリーチ", 2004, "Studio Pierrot", "TV", 366, "Finished Airing",
     ["Action", "Adventure", "Shounen", "Supernatural"], 8.1,
     "Ichigo Kurosaki devient Shinigami après avoir rencontré Rukia et protège les humains contre les Hollows."),
    ("Dragon Ball Z", "ドラゴンボールZ", 1989, "Toei Animation", "TV", 291, "Finished Airing",
     ["Action", "Adventure", "Martial Arts"], 8.2,
     "Goku et ses compagnons défendent la Terre contre des ennemis toujours plus puissants venus de l'espace."),
    ("Tokyo Ghoul", "東京喰種", 2014, "Studio Pierrot", "TV", 12, "Finished Airing",
     ["Action", "Horror", "Supernatural"], 7.8,
     "Ken Kaneki devient à moitié goule après une transplantation d'organes et doit naviguer entre deux mondes."),
    ("Parasyte", "寄生獣", 2014, "Madhouse", "TV", 24, "Finished Airing",
     ["Action", "Horror", "Sci-Fi"], 8.3,
     "Des parasites venus de l'espace envahissent des humains, mais l'un d'eux échoue à prendre le contrôle de Shinichi."),
    ("Made in Abyss", "メイドインアビス", 2017, "Kinema Citrus", "TV", 13, "Finished Airing",
     ["Adventure", "Drama", "Fantasy", "Mystery"], 8.7,
     "Riko et son compagnon robot Reg descendent dans un immense gouffre mystérieux pour retrouver la mère de Riko."),
    ("Re:Zero", "Re:ゼロから始める異世界生活", 2016, "White Fox", "TV", 25, "Finished Airing",
     ["Drama", "Fantasy", "Psychological", "Thriller"], 8.2,
     "Subaru est transporté dans un autre monde et découvre qu'il peut revenir dans le temps à chaque fois qu'il meurt."),
    ("Violet Evergarden", "ヴァイオレット・エヴァーガーデン", 2018, "Kyoto Animation", "TV", 13, "Finished Airing",
     ["Drama", "Fantasy", "Slice of Life"], 8.7,
     "Violet, une ancienne enfant-soldat, apprend à comprendre les émotions humaines en devenant écrivaine de lettres."),
    ("Clannad: After Story", "クラナド アフターストーリー", 2008, "Kyoto Animation", "TV", 24, "Finished Airing",
     ["Drama", "Romance", "Slice of Life", "Supernatural"], 8.9,
     "Tomoya et Nagisa entrent dans la vie adulte et font face aux défis du mariage, du travail et de la famille."),
    ("Monster", "モンスター", 2004, "Madhouse", "TV", 74, "Finished Airing",
     ["Drama", "Mystery", "Psychological", "Thriller"], 8.9,
     "Le Dr Tenma sauve la vie d'un jeune garçon qui se révèle être un dangereux criminel, et part à sa recherche à travers l'Europe."),
    ("Psycho-Pass", "サイコパス", 2012, "Production I.G", "TV", 22, "Finished Airing",
     ["Action", "Sci-Fi", "Thriller"], 8.3,
     "Dans un futur où un système juge en temps réel le potentiel criminel de chacun, l'inspectrice Akane Tsunemori doute du système."),
    ("Gintama", "銀魂", 2006, "Sunrise", "TV", 201, "Finished Airing",
     ["Action", "Comedy", "Historical", "Sci-Fi"], 8.9,
     "Dans un Japon d'Edo envahi par des extraterrestres, Gintoki Sakata dirige une entreprise à tout faire."),
    ("Haikyuu!!", "ハイキュー!!", 2014, "Production I.G", "TV", 25, "Finished Airing",
     ["Comedy", "Drama", "School", "Sports"], 8.5,
     "Hinata Shoyo rejoint le club de volley-ball du lycée Karasuno pour devenir le meilleur joueur malgré sa petite taille."),
    ("Kaguya-sama: Love is War", "かぐや様は告らせたい", 2019, "A-1 Pictures", "TV", 12, "Finished Airing",
     ["Comedy", "Psychological", "Romance", "School"], 8.4,
     "Kaguya et Miyuki sont trop fiers pour avouer leurs sentiments et se livrent à une guerre psychologique pour faire confesser l'autre."),
    ("The Promised Neverland", "約束のネバーランド", 2019, "CloverWorks", "TV", 12, "Finished Airing",
     ["Horror", "Mystery", "Psychological", "Sci-Fi"], 8.5,
     "Trois orphelins découvrent la terrible vérité sur leur orphelinat et planifient leur évasion."),
    ("Dr. Stone", "ドクターストーン", 2019, "TMS Entertainment", "TV", 24, "Finished Airing",
     ["Adventure", "Sci-Fi", "Shounen"], 8.2,
     "Après une pétrification mondiale, Senku se réveille 3700 ans plus tard et entreprend de reconstruire la civilisation avec la science."),
    ("Chainsaw Man", "チェンソーマン", 2022, "MAPPA", "TV", 12, "Finished Airing",
     ["Action", "Horror", "Supernatural"], 8.5,
     "Denji fusionne avec son démon-chien et devient Chainsaw Man, un chasseur de démons travaillant pour une agence spéciale."),
    ("Spy x Family", "スパイファミリー", 2022, "Wit Studio", "TV", 25, "Finished Airing",
     ["Action", "Comedy", "Slice of Life"], 8.5,
     "Un espion, une assassine et une télépathe forment une fausse famille pour chacun accomplir leur mission secrète."),
    ("Cyberpunk: Edgerunners", "サイバーパンク エッジランナーズ", 2022, "Studio Trigger", "ONA", 10, "Finished Airing",
     ["Action", "Drama", "Sci-Fi"], 8.6,
     "David, un jeune de Night City, s'implante un prototype militaire illégal et rejoint une équipe de mercenaires."),
    ("Bocchi the Rock!", "ぼっち・ざ・ろっく!", 2022, "CloverWorks", "TV", 12, "Finished Airing",
     ["Comedy", "Music", "Slice of Life"], 8.8,
     "Bocchi, une adolescente extrêmement timide, rejoint un groupe de rock malgré sa peur des interactions sociales."),
    ("Frieren: Beyond Journey's End", "葬送のフリーレン", 2023, "Madhouse", "TV", 28, "Finished Airing",
     ["Adventure", "Drama", "Fantasy"], 9.3,
     "Après avoir vaincu le Roi Démon, l'elfe Frieren reprend la route pour comprendre ce qu'elle a partagé avec ses compagnons mortels."),
    ("Oshi no Ko", "推しの子", 2023, "Doga Kobo", "TV", 11, "Finished Airing",
     ["Drama", "Supernatural"], 8.7,
     "Un médecin et une de ses patientes décédées renaissent comme les jumeaux d'une idole de J-pop."),
    ("Jujutsu Kaisen Season 2", "呪術廻戦 第2期", 2023, "MAPPA", "TV", 23, "Finished Airing",
     ["Action", "School", "Supernatural"], 8.8,
     "La suite des aventures de Yuji Itadori avec l'arc Shibuya Incident."),
    ("Mushishi", "蟲師", 2005, "Artland", "TV", 26, "Finished Airing",
     ["Adventure", "Historical", "Mystery", "Supernatural"], 8.7,
     "Ginko parcourt le Japon rural pour aider ceux qui sont affectés par les Mushi, des créatures surnaturelles primitives."),
    ("Ergo Proxy", "エルゴプラクシー", 2006, "Manglobe", "TV", 23, "Finished Airing",
     ["Mystery", "Psychological", "Sci-Fi"], 7.8,
     "Dans une ville-dôme futuriste, l'inspectrice Re-l Mayer enquête sur une série de meurtres liés à d'étranges créatures."),
    ("Serial Experiments Lain", "シリアルエクスペリメンツ レイン", 1998, "Triangle Staff", "TV", 13, "Finished Airing",
     ["Mystery", "Psychological", "Sci-Fi"], 8.0,
     "Lain, une adolescente timide, est entraînée dans les mystères du Wired, un réseau qui commence à fusionner avec la réalité."),
    ("Ghost in the Shell: SAC", "攻殻機動隊 STAND ALONE COMPLEX", 2002, "Production I.G", "TV", 26, "Finished Airing",
     ["Action", "Mecha", "Mystery", "Sci-Fi"], 8.4,
     "La Section 9 enquête sur des crimes cybernétiques dans un futur où l'humanité est partiellement cybernétisée."),
    ("Trigun", "トライガン", 1998, "Madhouse", "TV", 26, "Finished Airing",
     ["Action", "Adventure", "Comedy", "Sci-Fi"], 8.2,
     "Vash the Stampede, un hors-la-loi pacifiste avec une prime astronomique sur sa tête, erre dans un désert post-apocalyptique."),
    ("Samurai Champloo", "サムライチャンプルー", 2004, "Manglobe", "TV", 26, "Finished Airing",
     ["Action", "Adventure", "Historical"], 8.5,
     "Fuu entraîne deux samouraïs rivaux dans sa quête pour retrouver un mystérieux samouraï qui sent le tournesol."),
    ("FLCL", "フリクリ", 2000, "Gainax", "OVA", 6, "Finished Airing",
     ["Action", "Comedy", "Sci-Fi"], 7.8,
     "La vie de Naota bascule quand Haruko, une extraterrestre au scooter, le percute et libère un robot de son front."),
    ("Nichijou", "日常", 2011, "Kyoto Animation", "TV", 26, "Finished Airing",
     ["Comedy", "School", "Slice of Life"], 8.5,
     "La vie quotidienne absurde de trois lycéennes et d'une fillette-robot dans une petite ville japonaise."),
    ("K-On!", "けいおん!", 2009, "Kyoto Animation", "TV", 13, "Finished Airing",
     ["Comedy", "Music", "School", "Slice of Life"], 7.8,
     "Quatre lycéennes forment un groupe de rock pour sauver le club de musique légère de leur école."),
    ("The Melancholy of Haruhi Suzumiya", "涼宮ハルヒの憂鬱", 2006, "Kyoto Animation", "TV", 14, "Finished Airing",
     ["Comedy", "Mystery", "School", "Sci-Fi"], 7.8,
     "Kyon rejoint malgré lui la brigade SOS d'Haruhi Suzumiya, qui cherche des extraterrestres, voyageurs temporels et espers."),
    ("Lucky Star", "らき☆すた", 2007, "Kyoto Animation", "TV", 24, "Finished Airing",
     ["Comedy", "School", "Slice of Life"], 7.7,
     "Konata et ses amies lycéennes passent leurs journées à discuter d'otakeries et de sujets triviaux."),
    ("Toradora!", "とらドラ!", 2008, "J.C.Staff", "TV", 25, "Finished Airing",
     ["Comedy", "Romance", "School"], 8.1,
     "Ryuji et Taiga, deux lycéens mal compris, s'allient pour aider chacun à conquérir le béguin de l'autre."),
    ("Clannad", "クラナド", 2007, "Kyoto Animation", "TV", 23, "Finished Airing",
     ["Comedy", "Drama", "Romance", "School"], 8.0,
     "Tomoya, un lycéen désabusé, rencontre Nagisa et commence à s'impliquer dans la vie des filles qui l'entourent."),
    ("Angel Beats!", "エンジェルビーツ!", 2010, "P.A. Works", "TV", 13, "Finished Airing",
     ["Action", "Comedy", "Drama", "School", "Supernatural"], 8.1,
     "Otonashi se réveille dans un purgatoire lycéen où des élèves luttent contre Dieu pour ne pas disparaître."),
    ("Anohana", "あの日見た花の名前を僕達はまだ知らない", 2011, "A-1 Pictures", "TV", 11, "Finished Airing",
     ["Drama", "Slice of Life", "Supernatural"], 8.3,
     "Jinta voit un jour le fantôme de son amie d'enfance Menma, qui lui demande de réaliser son souhait pour qu'elle puisse reposer en paix."),
    ("A Silent Voice", "聲の形", 2016, "Kyoto Animation", "Movie", 1, "Finished Airing",
     ["Drama", "Romance", "School"], 8.9,
     "Shoya cherche à se racheter auprès de Shoko, une camarade de classe sourde qu'il avait persécutée en primaire."),
    ("Weathering with You", "天気の子", 2019, "CoMix Wave Films", "Movie", 1, "Finished Airing",
     ["Drama", "Romance", "Supernatural"], 8.1,
     "Dans un Tokyo noyé sous la pluie, un adolescent rencontre une jeune fille capable de contrôler la météo."),
    ("Howl's Moving Castle", "ハウルの動く城", 2004, "Studio Ghibli", "Movie", 1, "Finished Airing",
     ["Adventure", "Drama", "Fantasy", "Romance"], 8.7,
     "Sophie, transformée en vieille femme par une sorcière, cherche refuge dans le château magique de Howl."),
    ("My Neighbor Totoro", "となりのトトロ", 1988, "Studio Ghibli", "Movie", 1, "Finished Airing",
     ["Adventure", "Fantasy"], 8.3,
     "Deux sœurs emménagent à la campagne et découvrent les créatures magiques de la forêt voisine, dont le grand Totoro."),
    ("Castle in the Sky", "天空の城ラピュタ", 1986, "Studio Ghibli", "Movie", 1, "Finished Airing",
     ["Adventure", "Fantasy", "Sci-Fi"], 8.2,
     "Pazu et Sheeta cherchent Laputa, une cité mythique flottant dans les nuages, poursuivis par pirates et militaires."),
    ("Nausicaä of the Valley of the Wind", "風の谷のナウシカ", 1984, "Topcraft", "Movie", 1, "Finished Airing",
     ["Adventure", "Fantasy", "Sci-Fi"], 8.4,
     "Dans un monde post-apocalyptique, la princesse Nausicaä cherche à préserver la paix entre humains et nature."),
    ("Grave of the Fireflies", "火垂るの墓", 1988, "Studio Ghibli", "Movie", 1, "Finished Airing",
     ["Drama", "Historical"], 8.5,
     "Seita et Setsuko, deux enfants orphelins, tentent de survivre dans le Japon dévasté par la Seconde Guerre mondiale."),
    ("Akira", "アキラ", 1988, "Tokyo Movie Shinsha", "Movie", 1, "Finished Airing",
     ["Action", "Sci-Fi", "Supernatural"], 8.1,
     "Dans un Neo-Tokyo dystopique, Kaneda tente de sauver son ami Tetsuo dont les pouvoirs psychiques deviennent incontrôlables."),
    ("Ghost in the Shell (1995)", "攻殻機動隊", 1995, "Production I.G", "Movie", 1, "Finished Airing",
     ["Action", "Mecha", "Sci-Fi"], 8.3,
     "La major Motoko Kusanagi traque un hacker insaisissable appelé le Marionnettiste."),
    ("Perfect Blue", "パーフェクトブルー", 1997, "Madhouse", "Movie", 1, "Finished Airing",
     ["Drama", "Horror", "Psychological", "Thriller"], 8.4,
     "Mima, une idole reconvertie en actrice, est harcelée par un fan et commence à perdre pied avec la réalité."),
    ("Paprika", "パプリカ", 2006, "Madhouse", "Movie", 1, "Finished Airing",
     ["Mystery", "Psychological", "Sci-Fi"], 8.0,
     "Le Dr Atsuko Chiba utilise un appareil qui permet d'entrer dans les rêves des patients, jusqu'à ce qu'il soit volé."),
    ("Millennium Actress", "千年女優", 2001, "Madhouse", "Movie", 1, "Finished Airing",
     ["Drama", "Historical", "Romance"], 8.2,
     "Une actrice à la retraite raconte sa vie et se retrouve à revivre ses films et ses amours passées."),
    ("Tokyo Godfathers", "東京ゴッドファーザーズ", 2003, "Madhouse", "Movie", 1, "Finished Airing",
     ["Comedy", "Drama"], 8.3,
     "Trois sans-abri trouvent un bébé abandonné la veille de Noël à Tokyo et cherchent ses parents."),
    ("Redline", "REDLINE", 2010, "Madhouse", "Movie", 1, "Finished Airing",
     ["Action", "Sci-Fi", "Sports"], 8.1,
     "JP participe à la course galactique la plus dangereuse et illégale de l'univers : la Redline."),
    ("Summer Wars", "サマーウォーズ", 2009, "Madhouse", "Movie", 1, "Finished Airing",
     ["Comedy", "Sci-Fi"], 7.9,
     "Kenji est entraîné dans une cyberguerre qui menace le monde réel depuis un réseau social planétaire."),
    ("The Girl Who Leapt Through Time", "時をかける少女", 2006, "Madhouse", "Movie", 1, "Finished Airing",
     ["Adventure", "Drama", "Romance", "Sci-Fi"], 8.1,
     "Makoto découvre qu'elle peut sauter dans le temps, mais chaque voyage a des conséquences qu'elle ne maîtrise pas."),
    ("Wolf Children", "おおかみこどもの雨と雪", 2012, "Studio Chizu", "Movie", 1, "Finished Airing",
     ["Drama", "Fantasy"], 8.2,
     "Hana élève seule ses deux enfants mi-humains mi-loups après la mort de leur père."),
    ("A Place Further than the Universe", "宇宙よりも遠い場所", 2018, "Madhouse", "TV", 13, "Finished Airing",
     ["Adventure", "Comedy", "Drama"], 8.5,
     "Quatre lycéennes embarquent pour une expédition en Antarctique, chacune cherchant à accomplir un rêve personnel."),
    ("March Comes in Like a Lion", "3月のライオン", 2016, "Shaft", "TV", 22, "Finished Airing",
     ["Drama", "Slice of Life"], 8.4,
     "Rei Kiriyama, jeune joueur professionnel de shogi, lutte contre la solitude et la dépression avec l'aide de trois sœurs."),
    ("Beastars", "ビースターズ", 2019, "Orange", "TV", 12, "Finished Airing",
     ["Drama", "Psychological", "Slice of Life"], 7.8,
     "Dans un monde peuplé d'animaux anthropomorphes, le loup Legosi lutte contre ses instincts carnivores au lycée."),
    ("Dorohedoro", "ドロヘドロ", 2020, "MAPPA", "TV", 12, "Finished Airing",
     ["Action", "Comedy", "Horror", "Sci-Fi"], 8.2,
     "Caiman, un homme à tête de lézard, cherche le sorcier qui l'a transformé dans le quartier des magiciens."),
    ("Durarara!!", "デュラララ!!", 2010, "Brain's Base", "TV", 24, "Finished Airing",
     ["Action", "Mystery", "Supernatural"], 8.2,
     "À Ikebukuro, des gangs, une motarde sans tête et un informateur manipulateur tissent une toile complexe."),
    ("Baccano!", "バッカーノ!", 2007, "Brain's Base", "TV", 13, "Finished Airing",
     ["Action", "Comedy", "Historical", "Mystery"], 8.4,
     "Dans les années 1930, différentes histoires impliquant mafieux, alchimistes immortels et voleurs s'entrecroisent."),
    ("91 Days", "91デイズ", 2016, "Shuka", "TV", 12, "Finished Airing",
     ["Action", "Drama", "Historical"], 8.0,
     "Pendant la Prohibition, Avilio revient dans sa ville natale pour se venger de la famille mafieuse qui a tué sa famille."),
    ("Black Lagoon", "ブラック・ラグーン", 2006, "Madhouse", "TV", 12, "Finished Airing",
     ["Action", "Seinen"], 8.0,
     "Rock, un salaryman japonais, est kidnappé par des pirates et finit par rejoindre leur équipage de contrebandiers."),
    ("Berserk (1997)", "剣風伝奇ベルセルク", 1997, "OLM", "TV", 25, "Finished Airing",
     ["Action", "Adventure", "Drama", "Fantasy", "Horror"], 8.5,
     "Guts, un mercenaire au passé tragique, rejoint la bande de mercenaires du charismatique Griffith."),
    ("Berserk: The Golden Age Arc", "ベルセルク 黄金時代篇", 2012, "Studio 4°C", "Movie", 1, "Finished Airing",
     ["Action", "Adventure", "Drama", "Fantasy"], 8.0,
     "L'adaptation cinématographique de l'arc de l'Âge d'Or du manga Berserk."),
    ("Durarara!!x2", "デュラララ!!×2", 2015, "Shuka", "TV", 12, "Finished Airing",
     ["Action", "Mystery", "Supernatural"], 7.8,
     "Les évènements mystérieux à Ikebukuro continuent avec de nouveaux personnages et intrigues."),
    ("Akame ga Kill!", "アカメが斬る!", 2014, "White Fox", "TV", 24, "Finished Airing",
     ["Action", "Adventure", "Fantasy"], 7.5,
     "Tatsumi rejoint Night Raid, un groupe d'assassins qui lutte contre un empire corrompu."),
    ("No Game No Life", "ノーゲーム・ノーライフ", 2014, "Madhouse", "TV", 12, "Finished Airing",
     ["Adventure", "Comedy", "Fantasy"], 8.0,
     "Sora et Shiro, deux frères et sœurs génies du jeu, sont transportés dans un monde où tout se décide par des jeux."),
    ("Konosuba", "この素晴らしい世界に祝福を!", 2016, "Studio Deen", "TV", 10, "Finished Airing",
     ["Adventure", "Comedy", "Fantasy"], 8.1,
     "Kazuma est réincarné dans un monde de fantasy avec une déesse inutile, une magicienne explosive et une croisée masochiste."),
    ("Overlord", "オーバーロード", 2015, "Madhouse", "TV", 13, "Finished Airing",
     ["Action", "Adventure", "Fantasy", "Supernatural"], 7.9,
     "Momonga reste connecté à un MMO lors de sa fermeture et se retrouve transporté dans un monde virtuel devenu réel."),
    ("Sword Art Online", "ソードアート・オンライン", 2012, "A-1 Pictures", "TV", 25, "Finished Airing",
     ["Action", "Adventure", "Fantasy", "Game", "Romance"], 7.2,
     "10 000 joueurs sont piégés dans un MMO de réalité virtuelle où mourir dans le jeu signifie mourir dans la vraie vie."),
    ("Log Horizon", "ログ・ホライズン", 2013, "Satelight", "TV", 25, "Finished Airing",
     ["Action", "Adventure", "Fantasy", "Game"], 7.9,
     "Lorsqu'une mise à jour piège les joueurs dans un MMO, Shiroe s'efforce d'y bâtir une nouvelle société."),
    ("The Rising of the Shield Hero", "盾の勇者の成り上がり", 2019, "Kinema Citrus", "TV", 25, "Finished Airing",
     ["Action", "Adventure", "Drama", "Fantasy"], 7.8,
     "Naofumi est invoqué comme Héros du Bouclier dans un autre monde, trahi et humilié, il doit prouver sa valeur."),
    ("Goblin Slayer", "ゴブリンスレイヤー", 2018, "White Fox", "TV", 12, "Finished Airing",
     ["Action", "Adventure", "Fantasy"], 7.4,
     "Un aventurier obsédé par l'extermination des gobelins refuse toutes les autres quêtes."),
    ("That Time I Got Reincarnated as a Slime", "転生したらスライムだった件", 2018, "Eight Bit", "TV", 24, "Finished Airing",
     ["Action", "Adventure", "Comedy", "Fantasy"], 8.0,
     "Un salaryman japonais meurt et se réincarne en slime dans un monde fantastique qu'il va transformer."),
    ("Mushoku Tensei", "無職転生 ～異世界行ったら本気だす～", 2021, "Studio Bind", "TV", 11, "Finished Airing",
     ["Adventure", "Drama", "Ecchi", "Fantasy"], 8.4,
     "Un NEET de 34 ans meurt et se réincarne en bébé dans un monde de magie, déterminé à vivre pleinement cette fois-ci."),
    ("86", "エイティシックス", 2021, "A-1 Pictures", "TV", 11, "Finished Airing",
     ["Action", "Drama", "Mecha", "Sci-Fi"], 8.3,
     "Dans une république en guerre, des soldats officiellement 'sans race' combattent dans des mechas commandés à distance."),
    ("Odd Taxi", "オッドタクシー", 2021, "OLM", "TV", 13, "Finished Airing",
     ["Drama", "Mystery"], 8.5,
     "Un chauffeur de taxi morse introverti se retrouve au cœur d'une affaire de disparition à Tokyo."),
    ("Ranking of Kings", "王様ランキング", 2021, "Wit Studio", "TV", 23, "Finished Airing",
     ["Adventure", "Drama", "Fantasy"], 8.5,
     "Bojji, un jeune prince sourd et sans force, rêve de devenir le plus grand roi du monde."),
    ("Sonny Boy", "サニーボーイ", 2021, "Madhouse", "TV", 12, "Finished Airing",
     ["Drama", "Mystery", "Sci-Fi", "Supernatural"], 7.7,
     "Un groupe de lycéens se retrouve piégé dans une dimension parallèle à la dérive entre les mondes."),
    ("Lycoris Recoil", "リコリス・リコイル", 2022, "A-1 Pictures", "TV", 13, "Finished Airing",
     ["Action"], 8.2,
     "Deux adolescentes tueuses à gages travaillent dans un café qui sert de couverture à une organisation secrète."),
    ("Blue Lock", "ブルーロック", 2022, "Eight Bit", "TV", 24, "Finished Airing",
     ["Drama", "Sports"], 7.8,
     "Pour créer le meilleur attaquant du monde, 300 jeunes footballeurs sont enfermés dans un centre d'entraînement impitoyable."),
    ("Mushoku Tensei Season 2", "無職転生 II", 2023, "Studio Bind", "TV", 12, "Finished Airing",
     ["Adventure", "Drama", "Fantasy"], 8.2,
     "La suite des aventures de Rudeus dans le monde de magie."),
    ("Undead Unluck", "アンデッドアンラック", 2023, "David Production", "TV", 24, "Finished Airing",
     ["Action", "Comedy", "Supernatural"], 8.0,
     "Fuuko, une jeune femme porteuse d'une malédiction qui tue ceux qu'elle touche, rencontre Andy, un immortel qui cherche à mourir."),
]

# On injecte quelques pièges pédagogiques sur des entrées ciblées
# (valeurs manquantes, structure différente, etc.)
# Indices basés sur la liste ci-dessus.
ANOMALIES = {
    # index -> (score=None, studio_empty)
    7: {"score_na": True},      # Demon Slayer score "N/A"
    15: {"studio_empty": True}, # Neon Genesis Evangelion, studio vide
    22: {"score_na": True},     # Tokyo Ghoul
    47: {"studio_empty": True}, # Trigun
    50: {"score_na": True},     # Nichijou
    81: {"studio_empty": True}, # Berserk Golden Age Arc
    95: {"score_na": True},     # Sonny Boy
}


# Actualités saisonnières — pour l'aspect "nouveautés" mentionné dans le contexte
NEWS = [
    ("Les animes les plus attendus du printemps 2026", "2026-04-01", "Saisonnier",
     "La nouvelle saison démarre avec plusieurs suites très attendues. Les studios Wit Studio et MAPPA dominent à nouveau le calendrier avec des productions ambitieuses. Retrouvez notre sélection des 10 incontournables de la saison."),
    ("Studio Ghibli annonce un nouveau long-métrage", "2026-03-28", "Industrie",
     "Le studio Ghibli a confirmé le développement d'un nouveau film d'animation réalisé par un réalisateur émergent. La sortie est prévue pour l'été 2027."),
    ("Frieren saison 2 : première bande-annonce dévoilée", "2026-03-25", "Nouveauté",
     "Madhouse a publié la première bande-annonce officielle de la deuxième saison de Frieren, adaptant l'arc du Nord."),
    ("Bilan des audiences de la saison hiver 2026", "2026-03-20", "Analyse",
     "La saison hiver a été marquée par plusieurs succès inattendus. Le studio A-1 Pictures enregistre ses meilleures audiences depuis 2020."),
    ("Chainsaw Man : le film confirme sa date de sortie", "2026-03-15", "Industrie",
     "MAPPA a confirmé la sortie du film Chainsaw Man : Reze Arc pour le 12 septembre 2026 dans les cinémas japonais."),
    ("Le marché de l'anime dépasse les 3 mille milliards de yens", "2026-03-10", "Industrie",
     "L'Association des Animations Japonaises a publié son rapport annuel : le marché mondial de l'anime continue sa croissance avec une hausse de 12% par rapport à 2024."),
    ("Jujutsu Kaisen : le manga se termine, quid de l'anime ?", "2026-03-05", "Actualité",
     "Avec la fin du manga, les fans s'interrogent sur la suite de l'adaptation animée. MAPPA n'a pas encore fait d'annonce officielle."),
    ("Netflix renforce son catalogue anime pour 2026", "2026-02-28", "Industrie",
     "La plateforme de streaming a annoncé 15 nouvelles productions originales anime pour l'année 2026, dont plusieurs collaborations avec des studios japonais majeurs."),
]
